# Dockerfile

FROM node:10 as BUILD
COPY . .
RUN npm run build

FROM nginx:alpine
ENV TZ Asia/Seoul
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
EXPOSE 80
COPY --from=BUILD dist /usr/share/nginx/html
