# Dockerfile

FROM node:10 as BUILD
COPY . .
RUN npm run build

FROM nginx:1.13
ENV TZ Asia/Seoul
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apk add --no-cache bash
EXPOSE 80
COPY --from=BUILD dist /usr/share/nginx/html
